version: '3.7'
services:
  postgres:
    image: postgres:10.8
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: "mypgpass"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: 
networks: 
  backend:
    driver: bridge
